### ISSUE TITLE
Bot fails to perform sparql query with MaxlagTimeoutError

### ISSUE THREAD

**Issue by konstin** [konstin/github-wikidata-bot#115]
I've tried the query at https://query.wikidata.org/ and it seems to work, so I don't know what's stopping the bot here.

```
Traceback (most recent call last):
  File "./main.py", line 844, in <module>
    main()
  File "./main.py", line 808, in main
    response = sparql.SparqlQuery().query(sparql_license_items)
  File "[...]/.venv/lib/python3.6/site-packages/pywikibot/data/sparql.py", line 63, in __init__
    self.endpoint = repo.sparql_endpoint
  File "[...]/.venv/lib/python3.6/site-packages/pywikibot/site/__init__.py", line 1360, in callee
    if MediaWikiVersion(self.version()) < MediaWikiVersion(version):
  File "[...]/.venv/lib/python3.6/site-packages/pywikibot/site/__init__.py", line 2746, in version
    expiry=1).split(' ')[1]
  File "[...]/.venv/lib/python3.6/site-packages/pywikibot/site/__init__.py", line 1682, in get
    preloaded = self._get_general(key, expiry)
  File "[...]/.venv/lib/python3.6/site-packages/pywikibot/site/__init__.py", line 1628, in _get_general
    default_info = self._get_siteinfo(props, expiry)
  File "[...]/.venv/lib/python3.6/site-packages/pywikibot/site/__init__.py", line 1551, in _get_siteinfo
    data = request.submit()
  File "[...]/.venv/lib/python3.6/site-packages/pywikibot/data/api.py", line 2251, in submit
    self._data = super(CachedRequest, self).submit()
  File "[...]/.venv/lib/python3.6/site-packages/pywikibot/data/api.py", line 2101, in submit
    raise MaxlagTimeoutError(msg)
pywikibot.exceptions.MaxlagTimeoutError: Maximum retries attempted due to maxlag without success.
```

**Comment by Nudin** [comment]
Did the bot just failed once or is it failing permanently? If it's not permanently we can ignore this. `maxlag` is an indicator for under how much load the servers are. Bots have to include a mechanism that stops them from running if `maxlag` is too big (recommended: `maxlag>5`). If this is the case, the bot will wait for some time and then try again.
Above error message indicates that maxlag was above the threshold for a long time so that a maximum number of retries has been reached.
If this happens often we might consider slightly increasing maxlag, increase the maximum number of retries or catch the exception, do a longer sleep (like 3 hours) and then restart.

**Comment by konstin** [comment]
It happened at least three times in a row now. It might be that this bot isn't the only one with a `@daily` cron job and just adding a delay / setting another start time might help.

**Comment by konstin** [comment]
Thanks for the info btw :+1:

**Comment by Nudin** [comment]
> It might be that this bot isn't the only one with a `@daily` cron job and just adding a delay / setting another start time might help.

Yes changing the start time to something else and within the hour might be a good idea. Increasing the random delay might be also good. Depending on your distribution/cron implementation its as easy to change `/etc/anacrontab` where @daily is usually defined.

**Comment by konstin** [comment]
Changed it to `0 5 * * *`, let's see if that helps.

**Comment by konstin** [comment]
Nope, unfortunately still the same error. Also happens when I try to run the job manually at odd times.

**Comment by Nudin** [comment]
Weird, lest test with more aggressive and enduring parameters.  Set these in the config file:

```
# Maxlag. Higher values are more aggressive in seeking access to the wiki.
maxlag = 8

# Maximum number of times to retry an API request before quitting.
max_retries = 30
# Minimum time to wait before resubmitting a failed API request.
retry_wait = 5
# Maximum time to wait before resubmitting a failed API request.
retry_max = 360
```

**Comment by Nudin** [comment]
Another idea would be moving the bot to toolforge. Maybe bots running there (more or less in the same server farm) are handled more generous?

**Comment by konstin** [comment]
Thank you very much, now it works!

**Comment by konstin** [comment]
Broke again, this time elsewhere :sob: 

```
Traceback (most recent call last):
  File "./main.py", line 844, in <module>
    main()
  File "./main.py", line 838, in main
    raise e
  File "./main.py", line 835, in main
    update_wikidata(properties, edit_group_hash)
  File "./main.py", line 648, in update_wikidata
    item.get()
[...]
    raise MaxlagTimeoutError(msg)
pywikibot.exceptions.MaxlagTimeoutError: Maximum retries attempted due to maxlag without success.
```

**Comment by konstin** [comment]
It now just seems to work most of the time, though I have no idea why or when it does or doesn't

**Comment by Nudin** [comment]
It depends on the load of the wikidata servers. The developement of the 'maxlag' value can be seen here:
https://grafana.wikimedia.org/d/000000156/wikidata-dispatch?orgId=1&fullscreen&panelId=22&from=now-30d&to=now (orange shaded is when it is above 5, that is the recommended threshold)

**Comment by Nudin** [comment]
PS: I analyzed the data and the maxlag value is in general lowest from 5 to 8 am UTC.
![Figure_1](https://user-images.githubusercontent.com/509205/86366320-edceb380-bc7a-11ea-90fc-a0509b34680e.png)
