### ISSUE TITLE
#36 (Adding git as protocol) crashes the bot

### ISSUE THREAD

**Issue by konstin** [konstin/github-wikidata-bot#40]
Apparently we got a new repository which actually executes the new code from #36 which now crashes the bot. I should have really tested that before deploying :no_mouth: 

```
Traceback (most recent call last):
  File "/home/bot/github-wikidata-bot/main.py", line 621, in <module>
    main()
  File "/home/bot/github-wikidata-bot/main.py", line 613, in main
    update_wikidata(properties)
  File "/home/bot/github-wikidata-bot/main.py", line 393, in update_wikidata
    do_normalize_url(item, wikidata, url_normalized, url_raw, q_value)
  File "/home/bot/github-wikidata-bot/main.py", line 368, in do_normalize_url
    get_or_create_qualifiers(repo, claim, Settings.properties["protocol"], "Q186055")
  File "/home/bot/github-wikidata-bot/main.py", line 122, in get_or_create_qualifiers
    return _get_or_create(claim.addQualifier, all_objects, repo, p_value, qualifier)
  File "/home/bot/github-wikidata-bot/main.py", line 95, in _get_or_create
    requested.setTarget(value)
  File "/home/bot/.local/share/virtualenvs/github-wikidata-bot-9LWmAbAf/lib/python3.5/site-packages/pywikibot/page.py", line 4975, in setTarget
    % (value, value_class))
ValueError: Q186055 is not type <class 'pywikibot.page.ItemPage'>.
<class 'ValueError'>
```

**Comment by Nudin** [comment]
Fixed. Sorry!
