### ISSUE TITLE
TypeError with anaconda

### ISSUE THREAD

**Issue by konstin** [konstin/github-wikidata-bot#43]
There is a type error with anaconda (not the python one):

```
# Querying Projects
2532 projects were found by the sparql query
1 projects remained after filtering
1 projects were found
# Processing projects
## Anaconda: http://www.wikidata.org/entity/Q483544
Falling back to tags.
Invalid version string 'B4.EWT.BROKE.SWAP'
Invalid version string 'BEFORE.PROGRESS.UI.CHANGE.OCT.2003'
Invalid version string 'BEFORE.RHPL.SWITCHOVER'
Invalid version string 'Before.Commiting.Milan.Docs.String.Review'
Invalid version string 'Before.MSF.kslvm.growing'
Invalid version string 'Before.rhpl.X.backend.port'
Invalid version string 'ERIK-BROKE-THINGS'
Invalid version string 'MSF.BEFORE.LDAP.KRB5.WINSTON.CHANGES'
Invalid version string 'RECONFIG.DIE.DIE.DIE'
Invalid version string 'after-nfs-mount-upgrade'
Invalid version string 'after-parted-1-6-changes'
Invalid version string 'after-taroon-merge'
Invalid version string 'after.bootloader.merge'
Invalid version string 'after.390.merge'
Invalid version string 'anaconcda-fairfax-beta-1'
Invalid version string 'anaconda-6-1-1-1'
Invalid version string 'anaconda-6-1-1-2'
Invalid version string 'anaconda-6-1-1-merge-2'
Invalid version string 'anaconda-6-1-1-release'
Invalid version string 'anaconda-6-1'
Invalid version string 'anaconda-6-2-base'
Invalid version string 'anaconda-6-2-beta1'
Invalid version string 'anaconda-6-2-beta2-tag'
Invalid version string 'anaconda-6-2-beta3-sparc-tag'
Invalid version string 'anaconda-6-2-beta3-tag'
Invalid version string 'anaconda-6-2-final-tag'
Invalid version string 'anaconda-6-2-sbe'
Invalid version string 'anaconda-6-2ha-base'
Invalid version string 'anaconda-6-2j-before-6-2-merge'
Invalid version string 'anaconda-6-2j-oracle-base'
Invalid version string 'anaconda-6-9-0-tag'
Invalid version string 'anaconda-6-9-1-tag'
Invalid version string 'anaconda-6-9-2-tag'
Invalid version string 'anaconda-6-9-4-tag'
Invalid version string 'anaconda-7-0-7-tag'
Invalid version string 'anaconda-7-0-80-tag'
Invalid version string 'anaconda-7-0-90-tag'
Invalid version string 'anaconda-7-0-alpha-base'
Invalid version string 'anaconda-7-0-ia64-base'
Invalid version string 'anaconda-7-0j-base'
Invalid version string 'anaconda-7-2-base'
Invalid version string 'anaconda-7.3-13.1'
Invalid version string 'anaconda-8-0-base'
Invalid version string 'anaconda-9-0-amd64-base'
Invalid version string 'anaconda-9-0-base'
Invalid version string 'anaconda-9.0-6.1'
Invalid version string 'anaconda-9.0.2-1.RHEL'
Invalid version string 'anaconda-9.0.2-2.RHEL'
Invalid version string 'anaconda-9.0.2-3.RHEL'
Invalid version string 'anaconda-9.0.2-4.RHEL'
Invalid version string 'anaconda-9.0.2-5.RHEL'
Invalid version string 'anaconda-9.0.2-6.RHEL'
Invalid version string 'anaconda-9.0.2-7.RHEL'
Invalid version string 'anaconda-9.0.2-8.RHEL'
Invalid version string 'anaconda-9.0.3-1.RHEL'
Invalid version string 'anaconda-9.0.3-2.RHEL'
Invalid version string 'anaconda-9.0.3-3.RHEL'
Invalid version string 'anaconda-9.0.3-4.RHEL'
Invalid version string 'anaconda-9.0.4-1.RHEL'
Invalid version string 'anaconda-9.0.4-2.RHEL'
Invalid version string 'anaconda-9.0.4-3.RHEL'
Invalid version string 'anaconda-9.0.5-1.RHEL'
Invalid version string 'anaconda-9.0.5-2.RHEL'
Invalid version string 'anaconda-9.0.5-3.RHEL'
Invalid version string 'anaconda-9.0.5-4.RHEL'
Invalid version string 'anaconda-9.0.5-5.RHEL'
Invalid version string 'anaconda-9.0.5-6.RHEL'
Invalid version string 'anaconda-9.1-1.RHEL'
Invalid version string 'anaconda-9.1-2.RHEL'
Invalid version string 'anaconda-9.1-3.RHEL'
Invalid version string 'anaconda-9.1-4.RHEL'
Invalid version string 'anaconda-9.1-5.RHEL'
Invalid version string 'anaconda-9.1-6.RHEL'
Invalid version string 'anaconda-9.1-7.RHEL'
Invalid version string 'anaconda-9.1.1-1.RHEL'
Invalid version string 'anaconda-9.1.1-2.RHEL'
Invalid version string 'anaconda-9.1.1-3.RHEL'
Invalid version string 'anaconda-9.1.1-4.RHEL'
Invalid version string 'anaconda-9.1.1-5.RHEL'
Invalid version string 'anaconda-9.1.1-6.RHEL'
Invalid version string 'anaconda-9.1.1-7.RHEL'
Invalid version string 'anaconda-9.1.2-1.RHEL'
Invalid version string 'anaconda-9.1.2-2.RHEL'
Invalid version string 'anaconda-9.1.3-1.RHEL'
Invalid version string 'anaconda-9.1.3-2.RHEL'
Invalid version string 'anaconda-9.1.5.1-1.RHEL'
Invalid version string 'anaconda-9.1.5.2-1.RHEL'
Invalid version string 'anaconda-9.1.5.5-1.RHEL'
Invalid version string 'anaconda-9.1.5.8-1.RHEL'
Invalid version string 'anaconda-9.1.6.0-1.RHEL'
Invalid version string 'anaconda-9.1.6.1-1.RHEL'
Invalid version string 'anaconda-9.1.6.2-1.RHEL'
Invalid version string 'anaconda-9.1.6.3-1.RHEL'
Invalid version string 'anaconda-9.1.6.4-1.RHEL'
Invalid version string 'anaconda-9.1.6.5-1.RHEL'
Invalid version string 'anaconda-9.1.6.6-1.RHEL'
Invalid version string 'anaconda-9.1.6.7-1.RHEL'
Invalid version string 'anaconda-9.1.6.8-1.RHEL'
Invalid version string 'anaconda-9.1.6.10-1.RHEL'
Invalid version string 'anaconda-9.1.6.11-1.RHEL'
Invalid version string 'anaconda-9.1.6.12-1.RHEL'
Invalid version string 'anaconda-9.1.6.13-1.RHEL'
Invalid version string 'anaconda-9.1.6.13-2.RHEL'
Invalid version string 'anaconda-9.1.6.14-1.RHEL'
Invalid version string 'anaconda-9.1.6.15-1.RHEL'
Invalid version string 'anaconda-9.1.6.17-1.RHEL'
Invalid version string 'anaconda-9.1.6.18-1.RHEL'
Invalid version string 'anaconda-9.1.6.19-1.RHEL'
Invalid version string 'anaconda-9.1.6.20-1.RHEL'
Invalid version string 'anaconda-10.0-3.1'
Invalid version string 'anaconda-11.1.2.195-1_vlan'
Invalid version string 'anaconda-11.4.1.36-1.rebrand-devel'
Invalid version string 'anaconda-11.4.1.36-1.rebranddevel'
Invalid version string 'anaconda-before-2.6'
Invalid version string 'anaconda-before-japanese-merge'
Invalid version string 'anaconda-before-rpm-head-changes'
Invalid version string 'anaconda-dispatch-base'
Invalid version string 'anaconda-fairfax-beta-1-2'
Invalid version string 'anaconda-fairfax-beta-1'
Invalid version string 'anaconda-fairfax-beta-2'
Invalid version string 'anaconda-fairfax-beta-3'
Invalid version string 'anaconda-fairfax-rc1'
Invalid version string 'anaconda-fairfax-rc2'
Invalid version string 'anaconda-gtk-2-0-base'
Invalid version string 'anaconda-hampton-base'
Invalid version string 'anaconda-hampton-beta-1'
Invalid version string 'anaconda-hampton-beta1-2'
Invalid version string 'anaconda-hampton-beta1-3'
Invalid version string 'anaconda-hampton-beta1-4'
Invalid version string 'anaconda-hampton-beta1-5'
Invalid version string 'anaconda-hampton-rescueloader-base'
Invalid version string 'anaconda-parted-base'
Invalid version string 'anaconda-s390-GA2'
Invalid version string 'anaconda-s390-new-tag6'
Invalid version string 'anaconda-s390-tag'
Invalid version string 'anaconda-s390-tag2'
Invalid version string 'anaconda-s390-tag3'
Invalid version string 'anaconda-s390-tag4'
Invalid version string 'anaconda-s390-tag5'
Invalid version string 'anaconda-s390-tag7'
Invalid version string 'anaconda-sparc-alpha-base'
Invalid version string 'anaconda.8.0.90'
Invalid version string 'ancaonda-fairfax-beta-3'
Invalid version string 'b4.msf.really.broke.x'
Invalid version string 'before-6-1-merge'
Invalid version string 'before-cambridge-monitor-query-change'
Invalid version string 'before-ccb-qu2-cleanup'
Invalid version string 'before-hampton-merge'
Invalid version string 'before-loader-switch'
Invalid version string 'before-nfs-mount-upgrade'
Invalid version string 'before-parted-1-6-changes'
Invalid version string 'before-rpm-4.1'
Invalid version string 'before-taroon-merge-2'
Invalid version string 'before-taroon-merge'
Invalid version string 'before-taroon-updates'
Invalid version string 'before.bootloader.merge'
Invalid version string 'before.jj.patch2'
Invalid version string 'before.kudzu.loader.patch'
Invalid version string 'before.libdir.changes'
Invalid version string 'before.po.msgmerge'
Invalid version string 'before.removing.utc'
Invalid version string 'before.390.merge'
Invalid version string 'config-migrate-base'
Invalid version string 'desc'
Invalid version string 'f7-base'
Invalid version string 'f8-base'
Invalid version string 'f17-pre-noloader-merge'
Invalid version string 'fc3-base'
Invalid version string 'fc4-base'
Invalid version string 'fc5-base'
Invalid version string 'hampton-post-HEAD-merge'
Invalid version string 'help'
Invalid version string 'i18n-update-from-sources-07-20-2001'
Invalid version string 'kudzu-r0-44'
Invalid version string 'kudzu-r0-46'
Invalid version string 'kudzu-r0-66'
Invalid version string 'kudzu-r0-69'
Invalid version string 'kudzu-r0-97'
Invalid version string 'kudzu-r0-98-10'
Invalid version string 'merge.with.pot'
Invalid version string 'merged-to-taroon'
Invalid version string 'pre-newcomps'
Invalid version string 'pre-tab-convert'
Invalid version string 'r0-7-1'
Invalid version string 'r0-7-2'
Invalid version string 'r0-7-3'
Invalid version string 'r0-7-4'
Invalid version string 'r0-7-5'
Invalid version string 'r0-7-9'
Invalid version string 'r0-7-11'
Invalid version string 'r0-8-2'
Invalid version string 'r0-8-6'
Invalid version string 'r0-8-7'
Invalid version string 'r0-8-10'
Invalid version string 'r0-8-11'
Invalid version string 'r0-8-14'
Invalid version string 'r0-9-0'
Invalid version string 'r0-9-1'
Invalid version string 'r0-9-2'
Invalid version string 'r0-49'
Invalid version string 'r4-3-17'
Invalid version string 'r6.1.beta1'
Invalid version string 'rhel4-base'
Invalid version string 'rhel5-base'
Invalid version string 's390-beforeheadmerge'
Invalid version string 'sent-alpnet'
Invalid version string 'start'
Invalid version string 'taroon-base'
Invalid version string 'taroon-emd-base'
Invalid version string 'taroon-merge-point'
Invalid version string 'taroon-pre-package-changes'
Invalid version string 'ttt-tag-will-be-removed'
Invalid version string 'workflow-change-base'
Traceback (most recent call last):
  File "./main.py", line 704, in <module>
    main()
  File "./main.py", line 696, in main
    update_wikidata(properties)
  File "./main.py", line 495, in update_wikidata
    stable_releases.sort(key=lambda x: LooseVersion(x["version"]))
  File "/usr/lib/python3.6/distutils/version.py", line 52, in __lt__
    c = self._cmp(other)
  File "/usr/lib/python3.6/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'int' and 'str'
<class 'TypeError'>
```

 * https://github.com/rhinstaller/anaconda
 * https://www.wikidata.org/wiki/Q483544

Also, anaconda has >2000 releases making the bot really slow, and the current caching apparently doesn't help.

**Comment by Nudin** [comment]
As instant fix, I added Q483544 to the blacklist.
About the slowdown: I feared that. We should probably skip all projects with more than 200 tags or something like that completely.

About the type-Error: will look into that later.
