### ISSUE TITLE
Bot crash on 21/22 July

### ISSUE THREAD

**Issue by Nudin** [konstin/github-wikidata-bot#45]
@konstin Tonight the bot ran successfully for 4 hours adding versions based on tags until it apparently crashed while editing PostCSS (Q27145544). I let the bot run locally with the same Item and had no problems. Logs in Gist where not updated.
Can you please look up what happened?

**Comment by konstin** [comment]
Yep, I got a mail that cron job crashed because a rate limit kicked in (which is weird since I have a bot flag and pywikibot slows down when the servers demand that). I hope that this was a singular event due to the huge number of new tags.

**Comment by konstin** [comment]
I manually triggered a new run and the same crash happend again :/

```
Traceback (most recent call last):
  File "./main.py", line 660, in <module>
    main()
  File "./main.py", line 652, in main
    update_wikidata(properties)
  File "./main.py", line 565, in update_wikidata
    release["date"],
  File "./main.py", line 203, in get_or_create_sources
    claim.addSources(sources)
  File "/home/utasart/.local/share/virtualenvs/github-wikidata-bot-9LWmAbAf/lib/python3.5/site-packages/pywikibot/page.py", line 5070, in addSources
    data = self.repo.editSource(self, claims, new=True, **kwargs)
  File "/home/utasart/.local/share/virtualenvs/github-wikidata-bot-9LWmAbAf/lib/python3.5/site-packages/pywikibot/site.py", line 1316, in callee
    return fn(self, *args, **kwargs)
  File "/home/utasart/.local/share/virtualenvs/github-wikidata-bot-9LWmAbAf/lib/python3.5/site-packages/pywikibot/site.py", line 7860, in editSource
    data = req.submit()
  File "/home/utasart/.local/share/virtualenvs/github-wikidata-bot-9LWmAbAf/lib/python3.5/site-packages/pywikibot/data/api.py", line 2217, in submit
    raise APIError(**result['error'])
pywikibot.data.api.APIError: failed-save: The save has failed. [messages:[{'parameters': [], 'html': {'*': 'The save has failed.'}, 'name': 'wikibase-api-failed-save'}, {'parameters': [], 'html': {'*': 'As an anti-abuse measure, you are limited from performing this action too many times in a short space of time, and you have exceeded this limit.\nPlease try again in a few minutes.'}, 'name': 'actionthrottledtext'}]; help:See https://www.wikidata.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.]
<class 'pywikibot.data.api.APIError'>
```

**Comment by konstin** [comment]
I wonder why this happens now but didn't happen with earlier big imports. In the worst case we have to add some manual offset ourselves

**Comment by Nudin** [comment]
Wikidata had some server-problems lately and therefore new, stricter throttling-ruels have been activated. This is probably the explanation why this happens at the moment. I'll try to look up how to deal with that.

**Comment by Nudin** [comment]
I set minthrottle=1 and put_throttle=1 – maybe that helps.
